// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohanfsjbrklmmmlmyapd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oYW5mc2picmtsbW1tbG15YXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDkwMTUsImV4cCI6MjA3MDEyNTAxNX0.ziL1eBaO1W0P-s2UAhAUWlf75VsEou9FraC05rwKYEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});